# .sync.yml
---
Gemfile:
  optional:
    ':development':
      - gem: 'puppet-resource_api'
      - gem: 'faraday'
      - gem: 'rspec-json_expectations'
spec/spec_helper.rb:
  mock_with: ':rspec'
Rakefile:
  requires:
    - 'puppet-strings/tasks'
.travis.yml:
  simplecov: true
